from . import journal_publication
from . import book_publication
from . import ict_pedagogy
from . import research_guidance
from . import research_project
from . import ipr
from . import research_award
from . import conference_paper
from . import research_proposal
from . import product_development
from . import self_development_fdp
from . import industrial_training
from . import popular_writings
