-- Migration to sync Supabase schema with current SQLAlchemy models
-- Generated to fix UndefinedColumn errors

-- 1. Update faculty table
ALTER TABLE IF EXISTS faculty ADD COLUMN IF NOT EXISTS role VARCHAR DEFAULT 'faculty';
ALTER TABLE IF EXISTS faculty ADD COLUMN IF NOT EXISTS department VARCHAR;

-- 2. Add common columns (faculty_id, department, document) to all Part A and Part B tables
-- And specific api_score/research_score columns

-- Part A Tables
ALTER TABLE IF EXISTS annual_confidential_report ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS annual_confidential_report ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS annual_confidential_report ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS annual_confidential_report ADD COLUMN IF NOT EXISTS api_score_hod DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS annual_confidential_report ADD COLUMN IF NOT EXISTS api_score_director DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS course_file ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS course_file ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS course_file ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS course_file ADD COLUMN IF NOT EXISTS api_score_faculty DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS course_file ADD COLUMN IF NOT EXISTS api_score_hod DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS departmental_activities ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS departmental_activities ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS departmental_activities ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS departmental_activities ADD COLUMN IF NOT EXISTS api_score_faculty DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS departmental_activities ADD COLUMN IF NOT EXISTS api_score_hod DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS industry_connect_activity ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS industry_connect_activity ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS industry_connect_activity ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS industry_connect_activity ADD COLUMN IF NOT EXISTS api_score_faculty DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS industry_connect_activity ADD COLUMN IF NOT EXISTS api_score_hod DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS project ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS project ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS project ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS project ADD COLUMN IF NOT EXISTS api_score_faculty DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS project ADD COLUMN IF NOT EXISTS api_score_hod DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS qualification_enhancement ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS qualification_enhancement ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS qualification_enhancement ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS qualification_enhancement ADD COLUMN IF NOT EXISTS api_score_faculty DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS qualification_enhancement ADD COLUMN IF NOT EXISTS api_score_hod DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS contribution_to_society ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS contribution_to_society ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS contribution_to_society ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS contribution_to_society ADD COLUMN IF NOT EXISTS api_score_faculty DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS contribution_to_society ADD COLUMN IF NOT EXISTS api_score_hod DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS student_feedback ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS student_feedback ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS student_feedback ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS student_feedback ADD COLUMN IF NOT EXISTS api_score_faculty DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS student_feedback ADD COLUMN IF NOT EXISTS api_score_hod DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS innovative_teaching_methods ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS innovative_teaching_methods ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS innovative_teaching_methods ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS innovative_teaching_methods ADD COLUMN IF NOT EXISTS api_score_faculty DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS innovative_teaching_methods ADD COLUMN IF NOT EXISTS api_score_hod DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS teaching_process ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS teaching_process ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS teaching_process ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS teaching_process ADD COLUMN IF NOT EXISTS api_score_faculty DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS teaching_process ADD COLUMN IF NOT EXISTS api_score_hod DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS university_activities ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS university_activities ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS university_activities ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS university_activities ADD COLUMN IF NOT EXISTS api_score_faculty DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS university_activities ADD COLUMN IF NOT EXISTS api_score_hod DOUBLE PRECISION DEFAULT 0.0;

-- Part B Tables
ALTER TABLE IF EXISTS book_publications ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS book_publications ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS book_publications ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS book_publications ADD COLUMN IF NOT EXISTS api_score_faculty DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS book_publications ADD COLUMN IF NOT EXISTS api_score_hod DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS book_publications ADD COLUMN IF NOT EXISTS api_score_director DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS academic_events ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS academic_events ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS academic_events ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS academic_events ADD COLUMN IF NOT EXISTS research_score_faculty DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS academic_events ADD COLUMN IF NOT EXISTS research_score_hod DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS academic_events ADD COLUMN IF NOT EXISTS research_score_director DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS ict_teaching_content ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS ict_teaching_content ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS ict_teaching_content ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS ict_teaching_content ADD COLUMN IF NOT EXISTS api_score_faculty DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS ict_teaching_content ADD COLUMN IF NOT EXISTS api_score_hod DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS ict_teaching_content ADD COLUMN IF NOT EXISTS api_score_director DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS industrial_training ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS industrial_training ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS industrial_training ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS industrial_training ADD COLUMN IF NOT EXISTS api_score_faculty DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS industrial_training ADD COLUMN IF NOT EXISTS api_score_hod DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS industrial_training ADD COLUMN IF NOT EXISTS api_score_director DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS ipr ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS ipr ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS ipr ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS ipr ADD COLUMN IF NOT EXISTS api_score_faculty DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS ipr ADD COLUMN IF NOT EXISTS api_score_hod DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS ipr ADD COLUMN IF NOT EXISTS api_score_director DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS published_papers ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS published_papers ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS published_papers ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS published_papers ADD COLUMN IF NOT EXISTS api_score_faculty DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS published_papers ADD COLUMN IF NOT EXISTS api_score_hod DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS published_papers ADD COLUMN IF NOT EXISTS api_score_director DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS published_papers ADD COLUMN IF NOT EXISTS sr_no INTEGER;
ALTER TABLE IF EXISTS published_papers ADD COLUMN IF NOT EXISTS title_with_page_nos TEXT;
ALTER TABLE IF EXISTS published_papers ADD COLUMN IF NOT EXISTS journal_details TEXT;
ALTER TABLE IF EXISTS published_papers ADD COLUMN IF NOT EXISTS issn_isbn_no VARCHAR(50);
ALTER TABLE IF EXISTS published_papers ADD COLUMN IF NOT EXISTS indexing VARCHAR(20); 

ALTER TABLE IF EXISTS products_developed ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS products_developed ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS products_developed ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS products_developed ADD COLUMN IF NOT EXISTS api_score_faculty DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS products_developed ADD COLUMN IF NOT EXISTS api_score_hod DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS products_developed ADD COLUMN IF NOT EXISTS api_score_director DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS research_awards ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS research_awards ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS research_awards ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS research_awards ADD COLUMN IF NOT EXISTS api_score_faculty DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS research_awards ADD COLUMN IF NOT EXISTS api_score_hod DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS research_awards ADD COLUMN IF NOT EXISTS api_score_director DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS research_guidance ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS research_guidance ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS research_guidance ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS research_guidance ADD COLUMN IF NOT EXISTS api_score_faculty DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS research_guidance ADD COLUMN IF NOT EXISTS api_score_hod DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS research_guidance ADD COLUMN IF NOT EXISTS api_score_director DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS research_projects ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS research_projects ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS research_projects ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS research_projects ADD COLUMN IF NOT EXISTS api_score_faculty DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS research_projects ADD COLUMN IF NOT EXISTS api_score_hod DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS research_projects ADD COLUMN IF NOT EXISTS api_score_director DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS research_proposals ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS research_proposals ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS research_proposals ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS research_proposals ADD COLUMN IF NOT EXISTS api_score_faculty DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS research_proposals ADD COLUMN IF NOT EXISTS api_score_hod DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS research_proposals ADD COLUMN IF NOT EXISTS api_score_director DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS self_development ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS self_development ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS self_development ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS self_development ADD COLUMN IF NOT EXISTS api_score_faculty DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS self_development ADD COLUMN IF NOT EXISTS api_score_hod DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE IF EXISTS self_development ADD COLUMN IF NOT EXISTS api_score_director DOUBLE PRECISION DEFAULT 0.0;

-- 3. Overall / Remarks / Finalization Tables
ALTER TABLE IF EXISTS enclosure_text_block ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS enclosure_text_block ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS enclosure_text_block ADD COLUMN IF NOT EXISTS document VARCHAR;

ALTER TABLE IF EXISTS enclosure_declaration ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS enclosure_declaration ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS enclosure_declaration ADD COLUMN IF NOT EXISTS document VARCHAR;

ALTER TABLE IF EXISTS appraisal_remarks ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS appraisal_remarks ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS appraisal_remarks ADD COLUMN IF NOT EXISTS document VARCHAR;

ALTER TABLE IF EXISTS hod_remarks ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS hod_remarks ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS hod_remarks ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS hod_remarks ADD COLUMN IF NOT EXISTS hod_approved_score DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS director_remarks ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS director_remarks ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS director_remarks ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS director_remarks ADD COLUMN IF NOT EXISTS director_approved_score DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS dean_remarks ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS dean_remarks ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS dean_remarks ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS dean_remarks ADD COLUMN IF NOT EXISTS dean_approved_score DOUBLE PRECISION DEFAULT 0.0;

ALTER TABLE IF EXISTS final_approval ADD COLUMN IF NOT EXISTS faculty_id UUID REFERENCES faculty(id);
ALTER TABLE IF EXISTS final_approval ADD COLUMN IF NOT EXISTS department VARCHAR;
ALTER TABLE IF EXISTS final_approval ADD COLUMN IF NOT EXISTS document VARCHAR;
ALTER TABLE IF EXISTS final_approval ADD COLUMN IF NOT EXISTS final_score DOUBLE PRECISION DEFAULT 0.0;
