from .faculty import Faculty
from .journal_publication import JournalPublication
from .book_publication import BookPublication
from .ict_pedagogy import ICTPedagogy
from .research_guidance import ResearchGuidance
from .research_project import ResearchProject
from .ipr import IPR
from .research_award import ResearchAward
from .conference_paper import ConferencePaper
from .research_proposal import ResearchProposal
from .product_development import ProductDevelopment
from .self_development_fdp import SelfDevelopmentFDP
from .industrial_training import IndustrialTraining
from .popular_writings import PopularWriting
