from .teaching_process import TeachingProcess
from .course_file import CourseFile
from .teaching_methods import TeachingMethods
from .project import ProjectPartA
from .qualification_enhancement import QualificationEnhancement
from .student_feedback import StudentFeedback
from .departmental_activities import DepartmentalActivity
from .university_activities import UniversityActivity
from .social_contributions import SocialContribution
from .industry_connect import IndustryConnect
from .acr import ACR
