from . import teaching_process
from . import course_file
from . import teaching_methods
from . import project
from . import qualification_enhancement
from . import student_feedback
from . import departmental_activities
from . import university_activities
from . import social_contributions
from . import industry_connect
from . import acr
