from .journal_publication import *
from .book_publication import *
from .ict_pedagogy import *
from .research_guidance import *
from .research_project import *
from .ipr import *
from .research_award import *
from .conference_paper import *
from .research_proposal import *
from .product_development import *
from .self_development_fdp import *
from .industrial_training import *
