from .teaching_process import *
from .course_file import *
from .teaching_methods import *
from .project import *
from .qualification_enhancement import *
from .student_feedback import *
from .departmental_activities import *
from .university_activities import *
from .social_contributions import *
from .industry_connect import *
from .acr import *
